FROM rust@sha256:2f761161877d82470432d6d6de41b1a1a8c83d7dd255f076bffc89bff5cd4d0a AS builder
WORKDIR /usr/src/scylla

COPY Cargo.toml .
COPY Cargo.lock .

# Create dummy files to build the dependencies, cargo won't build without src/main.rs and src/lib.rs
# then remove Scylla fingerprint for following rebuild
RUN mkdir -p ./src/ && \
    echo 'fn main() {}' > ./src/main.rs && \
    echo '' > ./src/lib.rs
RUN cargo build --release && \
    rm -rf ./target/release/.fingerprint/scylla-*

# Build real binaries now
COPY ./src ./src
RUN cargo build --release

FROM arm64v8/debian:stretch-slim
WORKDIR /usr/app
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/scylla/target/release/scylla .
ENV RUST_LOG scylla=info
CMD ["./scylla"]