kind: ApplicationConfiguration
apiVersion: core.oam.dev/v1alpha1
metadata:
  name: "{{ .Release.Name }}"
spec:
  components:
    - componentName: "{{ .Release.Name }}-{{ .Values.appVersion}}"
      instanceName: "{{ .Release.Name }}-{{ .Values.appVersion}}"
      parameterValues:
        - name: target
          value: "{{ .Values.target }}"
        - name: port
          value: "{{ .Values.port }}"
      traits:
        - name: ingress.core.oam.dev/v1alpha1
          properties:
            hostname: example.com
            path: /
            servicePort: {{ .Values.port }}
        - name: manual-scaler.core.oam.dev/v1alpha1
          properties:
            replicaCount: {{ .Values.replicaCount }}
