FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app
EXPOSE 80

# copy csproj and restore as distinct layers
COPY . ./
RUN dotnet publish -c Release -o out /app/Profile.Api/Bikesharing.Profile.Api.csproj

# build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/Profile.Api/out .
ENTRYPOINT ["dotnet", "Bikesharing.Profile.Api.dll"]