# This will create a Horizontal Pod Autoscaler, but your cluster must have
# an implementation of an HPA before this will actually cause autoscaling.
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: autoscaler-example
spec:
  components:
    - componentName: hpa-example-replicated-v1
      instanceName: autoscaled-repsvc
      parameterValues:
        - name: poet
          value: Eliot
        - name: poem
          value: The Wasteland
      traits:
        - name: auto-scaler
          properties:
            maximum : 6
            minimum : 2
            cpu : 50
            memory : 50
