#
# To run this example, first create an image pull secret named 'example-image-pull-secret'
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# kubectl create secret docker-registry example-image-pull-secret --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
#

apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: image-pull-secret-example-v1
spec:
  workloadType: core.oam.dev/v1alpha1.Task
  osType: linux
  containers:
    - name: runner
      image: alpine:latest
      imagePullSecret: example-image-pull-secret
      resources:
        cpu:
          required: "0.1"
        memory:
          required: "128"
---
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: example-image-pull-secret-task
spec:
  components:
    - componentName: image-pull-secret-example-v1
      instanceName: one-image-pull-secret-task
      parameterValues:
        - name: message
          value: Hello World
