# Manual scaling is enabled by trait.
# This example shows how to apply a manual scaler to a replicatable service.
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: manual-scaler-example
spec:
  components:
    - componentName: nginx-replicated-v1
      instanceName: scaled-repsvc
      parameterValues:
        - name: poet
          value: Eliot
        - name: poem
          value: The Wasteland
      traits:
        - name: manual-scaler.core.oam.dev/v1alpha1
          properties:
            replicaCount: 3
