apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: example-multi-server
spec:
  components:
    - componentName: nginx-singleton-v1
      instanceName: multi-singleton-1
      traits:
        - name: ingress.core.oam.dev/v1alpha1
          parameterValues:
            hostname: example.com
            path: /
    - componentName: nginx-singleton-v1
      instanceName: multi-singleton-2
