apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: example-multi-component
spec:
  components:
    - name: nginx-singleton-v1
      instanceName: example-multi-component-nginx
      parameterValues:
        - name: poet
          value: Eliot
        - name: poem
          value: The Wasteland
      traits:
        - name: ingress
          parameterValues:
            - name: hostname
              value: example.com
            - name: path
              value: /
    - name: alpine-task-v1
      instanceName: example-multi-component-alpine
      parameterValues:
        - name: message
          value: Hello World
