apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: example-multi-component
spec:
  components:
    - componentName: nginx-singleton-v1
      instanceName: example-multi-component-nginx
      parameterValues:
        - name: poet
          value: Eliot
        - name: poem
          value: The Wasteland
      traits:
        - name: ingress.core.oam.dev/v1alpha1
          parameterValues:
            hostname: example.com
            path: /
    - componentName: alpine-task-v1
      instanceName: example-multi-component-alpine
      parameterValues:
        - name: message
          value: Hello World
