apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: nginx-component-v1
spec:
  name: nginx-component
  workloadType: core.oam.dev/v1alpha1.SingletonServer
  osType: linux
  arch: amd64
  containers:
    - name: foo
      image: nginx:latest
      cmd:
        - nginx-debug
      args:
        - "-g"
        - "daemon off;"
      env:
        - name: TEST
          value: FOO
      config:
        - path: "/etc/access/default_user.txt"
          value: "admin"
        - path: "/etc/run/db-data"
          fromParam: "poet"
      ports:
        - type: tcp
          containerPort: 80
          name: http
      resources:
        cpu:
          required: 0.1
        memory:
          required: "128"
  parameters:
    - name: poet
      type: string
      default: Yeats
    - name: poem
      type: string
      default: The Second Coming
