apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: openfaas
spec:
  workloadType: openfaas.com/v1alpha2.Function
  osType: linux
  parameters:
    - name: image
      type: string
      default: alexellisuk/go-echo:0.2.2
    - name: handler
      type: string
      default: ""
    - name: write_debug
      type: string
      default: "true"
  workloadSettings:
    - name: image
      type: string
      description: docker image name of this function
      fromParam: image
      value: alexellisuk/go-echo:0.2.2
      required: true
    - name: handler
      type: string
      description: entrypoint of your function, eg. node main.js
      required: false
      fromParam: handler
    - name: environment
      type: array
      description: environments of functions
      value:
        - name: write_debug
          type: string
          value: "true"
          fromParam: write_debug

---

apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: openfaas
spec:
  components:
    - componentName: openfaas
      instanceName: nodeinfo
      parameterValues:
        - name: image
          value: functions/nodeinfo
        - name: handler
          value: "node main.js"
        - name: write_debug
          value: "false"
      traits:
        - name: manual-scaler
          properties:
            replicaCount: 2