apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: example-replicable-task
spec:
  components:
    - componentName: alpine-task-v1
      instanceName: multi-alpine-task
      parameterValues:
        - name: message
          value: Hello World
      traits:
        - name: manual-scaler
          parameterValues:
            - name: replicaCount
              value: 3
