# This is a stand-alone example of using a volume with a component.
apiVersion: core.hydra.io/v1alpha1
kind: ComponentSchematic
metadata:
  name: server-with-volume-v1
spec:
  workloadType: core.hydra.io/v1alpha1.Server
  containers:
    - name: server
      image: nginx:latest
      resources:
        volumes:
          - name: myvol
            mountPath: /myvol
            disk:
              required: "200M"
              ephemeral: true
---
apiVersion: core.hydra.io/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: example-server-with-volume
spec:
  components:
    - name: server-with-volume-v1
      instanceName: example-server-with-volume
# TODO: Add trait to bind a PVC
