apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: worker-app
spec:
  components:
    - componentName: alpine-worker-v1
      instanceName: worker-nginx
      parameterValues:
        - name: poet
          value: Eliot
        - name: poem
          value: The Wasteland
      traits:
        - name: manual-scaler.core.oam.dev/v1alpha1
          properties:
            replicaCount: 2
