apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: worker-app
spec:
  components:
    - name: alpine-worker-v1
      instanceName: worker-nginx
      parameterValues:
        - name: poet
          value: Eliot
        - name: poem
          value: The Wasteland
      traits:
        - name: manual-scaler
          parameterValues:
            - name: replicaCount
              value: 2
