apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: healthscopes.core.hydra.io
  labels:
    app.kubernetes.io/part-of: core.hydra.io
spec:
  group: core.hydra.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: healthscopes
    singular: healthscope
    kind: HealthScope
    shortNames:
      - health