/* Copyright Microsoft */

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	corev1alpha1 "github.com/microsoft/scylla/pkg/apis/core/v1alpha1"
	versioned "github.com/microsoft/scylla/pkg/client/clientset/versioned"
	internalinterfaces "github.com/microsoft/scylla/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/microsoft/scylla/pkg/client/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// OperationalConfigurationInformer provides access to a shared informer and lister for
// OperationalConfigurations.
type OperationalConfigurationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.OperationalConfigurationLister
}

type operationalConfigurationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewOperationalConfigurationInformer constructs a new informer for OperationalConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewOperationalConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredOperationalConfigurationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredOperationalConfigurationInformer constructs a new informer for OperationalConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredOperationalConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().OperationalConfigurations(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().OperationalConfigurations(namespace).Watch(options)
			},
		},
		&corev1alpha1.OperationalConfiguration{},
		resyncPeriod,
		indexers,
	)
}

func (f *operationalConfigurationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredOperationalConfigurationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *operationalConfigurationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corev1alpha1.OperationalConfiguration{}, f.defaultInformer)
}

func (f *operationalConfigurationInformer) Lister() v1alpha1.OperationalConfigurationLister {
	return v1alpha1.NewOperationalConfigurationLister(f.Informer().GetIndexer())
}
