# This is a single-shot configuration that creates the entire Docker Voting app
# all in one go.
apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: voter-app
spec:
  components:
    - name: postgres-v9
      instanceName: voter-pg
    - name: redis-v1
      instanceName: voter-redis
    - name: voting-worker-v1
      instanceName: voter-worker
    - name: voting-frontend-v1
      instanceName: voter-fe
      traits:
        - name: ingress
          parameterValues:
            - name: hostname
              value: voting.example.com
            - name: path
              value: /
    - name: voting-admin-v1
      instanceName: voter-admin
      traits:
        - name: ingress
          parameterValues:
            - name: hostname
              value: admin.example.com
            - name: path
              value: /
