/* Copyright Microsoft */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// OperationalConfigurationListerExpansion allows custom methods to be added to
// OperationalConfigurationLister.
type OperationalConfigurationListerExpansion interface{}

// OperationalConfigurationNamespaceListerExpansion allows custom methods to be added to
// OperationalConfigurationNamespaceLister.
type OperationalConfigurationNamespaceListerExpansion interface{}
